site_name: Restify Experiment Replication Package
site_url: https://anonymous4doubleblinded.github.io/ExperimentReplicationPackage/
nav:
    - Welcome: index.md
    - Recruitment Material: recruitment.md
    - MiniMax Heuristic: minimax.md
    - Instructions: instructions.md
    - Applications: applications.md
    - Raw Data: data.md
    - Correctness Analyzer: analyzer.md
    - Times and Observations: observations.md
    - Interactive Notebook: notebook.md
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: blinded
    accent: red
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - tables
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

